HOTFIX: Fix compilation error in BrokerLifecycleManager (#14732)
This patch fixes a compilation error introduced by https://github.com/apache/kafka/pull/14392 for Scala 2.12.

```
> Task :core:compileScala

[Error] /home/jenkins/workspace/Kafka_kafka-pr_PR-14392/core/src/main/scala/kafka/server/BrokerLifecycleManager.scala:305:49: value incl is not a member of scala.collection.immutable.Set[org.apache.kafka.common.Uuid]
```

Reviewers: Luke Chen <showuon@gmail.com>